<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>e-Tiangge Taytay</title>
    <link rel="stylesheet" href="../style/terms.css">
    <link rel="stylesheet" href="../style/navandfoot.css">

</head>

<body>

    <div class="register">
        <p>Become a Seller? <a href="register.php">Register Now</a></p>
    </div>

    <!-- Navbar Section -->
    <nav class="navbar">
        <div class="left-side">
            <a href="#"><img src="../assets/shoppingbag.png" alt=""></a>
            <div class="input-with-icon">
                <img class="search-icon" src="../assets/Vector.png" alt="">
                <input type="text" placeholder="Search for Products...">
            </div>
        </div>
        <div class="right-side">
            <ul>
                <li><a href="#">Home</a></li>
                <li class="selected"><a href="about.php">About</a></li>
                <li><a href="products.php">Products</a></li>
                <li><a href="store.php">Store</a></li>
                <li><a href="contact.php">Contact us</a></li>
            </ul>
        </div>
    </nav>

    <section class="terms-conditions privacy">
        <h1>PRIVACY POLICY</h1>

        <h3>Introduction</h3>
        <p>At Taytay Tiangge Portal, We are committed to protecting Your privacy. This Privacy Policy describes our
            policies and procedures on the collection, use, and disclosure of Your information when You use the Service
            and tells You about Your privacy rights and how the law protects You.</p>
        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
            created with the help and collaboration of the owner and team project of this website.</p>
        <br><br>
        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
            <li><strong>Account</strong> means a unique account created for you to access our service or parts of our
                service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control
                with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other
                securities entitled to vote for the election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us", or "Our" in this Agreement)
                refers to Taytay Tiangge Portal.</li>
            <li><strong>Cookies</strong> are small files placed on your computer, mobile device, or any other device by
                a website, containing the details of your browsing history on that website, among other uses.</li>
            <li><strong>Device</strong> means any device that can access the service, such as a computer, cellphone, or
                digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable
                individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of
                the Company, including third-party companies or individuals employed by the Company to facilitate the
                service or perform services related to the service.</li>
            <li><strong>Third-party Social Media Service</strong> refers to any website or social network website
                through which a User can log in or create an account to use the Service.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
                Service or from the Service infrastructure itself (e.g., the duration of a page visit).</li>
            <li><strong>Website</strong> refers to Taytay Tiangge Portal, accessible from (http://www.taytaytiapor.com).
            </li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
                entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>
        <br><br>

        <h3>1. Information Collection</h3>
        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that
            can be used to contact or identify You. We collect the following types of information:</p>

        <h4>1.1 Personal Data</h4>
        <ul>
            <li>Name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <li>Address</li>
            <li>Date of birth and place of birth</li>
            <li>Gender</li>
            <li>Stall number and store name</li>
            <li>Business permit and DTI approval</li>
            <li>Images and biometric data, including photographs or audio or video recordings</li>
            <li>Geographic or location data</li>
            <li>Any other information about you provided when you access, visit, and/or interact with us or the Site
            </li>
            <li>Aggregate data on content you engage with</li>
        </ul>

        <h4>1.2 Usage Data</h4>
        <ul>
            <li>Device's Internet Protocol address (e.g., IP address)</li>
            <li>Browser type and browser version</li>
            <li>The pages of our Service that You visit, the time and date of Your visit, the time spent on those pages
            </li>
            <li>Unique device identifiers</li>
            <li>Activity on the Website</li>
            <li>Other diagnostic data on the system for analytics and security purposes</li>
        </ul>

        <h3>2. Information from Third-Party Social Media Services</h3>
        <p>The Company allows You to create an account and log in to use the service through the following Third-party
            Social Media Services:</p>
        <ul>
            <li>Google Analytics</li>
            <li>Facebook</li>
            <li>Shopee</li>
            <li>Lazada</li>
            <li>LinkedIn</li>
        </ul>
        <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may
            collect Personal data that is already associated with Your Third-Party Social Media Service's account, such
            as Your name, Your email address, Your activities, or Your contact list associated with that account.</p>
        <br><br>
        <h3>3. Tracking Technologies and Cookies</h3>
        <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
            information. Tracking technologies used include beacons, tags, and scripts to collect and track information
            and to improve and analyze Our Service.</p>
        <br><br>
        <h3>4. Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account and provide access to various Service functionalities.</li>
            <li>To contact You via email, phone, SMS, or other communication forms.</li>
            <li>For business transfers or in the event of a merger, acquisition, or sale.</li>
            <li>For data analysis, improving services, marketing, and user experience.</li>
        </ul>
        <br><br>
        <h3>5. Retention of Your Personal Data</h3>
        <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
            Privacy Policy.</p>
        <br><br>
        <h3>6. Transfer of Your Personal Data</h3>
        <p>Your information may be transferred to and maintained on servers located outside Your jurisdiction, where
            data protection laws may differ from those of Your country.</p>
        <br><br>
        <h3>7. Delete Your Personal Data</h3>
        <p>You have the right to request the deletion of your Personal Data under applicable laws.</p>
        <br><br>
        <h3>8. Disclosure of Your Personal Data</h3>
        <p>We may disclose your Personal Data in certain situations, such as business transactions, legal obligations,
            or to protect the rights of the Company.</p>
        <br><br>
        <h3>9. Security of Your Personal Data</h3>
        <p>We implement a variety of security measures to ensure the protection of your Personal Data, though no method
            of transmission or storage is completely secure.</p>
        <br><br>
        <h3>10. Links to Other Websites</h3>
        <p>Our Service may contain links to other websites that are not operated by Us. We are not responsible for the
            content or privacy practices of third-party sites.</p>
        <br><br>
        <h3>11. Changes to this Privacy Policy</h3>
        <p>We may update this Privacy Policy from time to time and will notify you of any changes by posting a new
            Privacy Policy on this page.</p>
        <br><br>
        <h3>12. Contact Us</h3>
        <p>If you have any questions or concerns about our Privacy Policy, please contact us at <a
                href="mailto:taytaytp@gmail.com">taytaytp@gmail.com</a>.</p>
        <p>Please include your name, contact information, and the nature of your request so that we can appropriately
            respond to your communication.</p>
    </section>

    <footer>
        <div class="top-footer">
            <div class="footer-logo">
                <img src="../assets/tianggeportal.png" alt="">
                <p>Find quality clothes and<br> garments in Taytay Tiangge<br> anytime and anywhere you are!</p>
            </div>

            <div class="footer-info">
                <h4 class="first-category">Information</h4>
                <ul>
                    <li><a href="about.php">About</a></li>
                    <li><a href="terms.php">Terms & Conditions</a></li>
                    <li><a href="privacy.php">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="footer-info">
                <h4 class="second-category">Categories</h4>
                <ul>
                    <li><a href="products.php">Men's Fashion</a></li>
                    <li><a href="products.php">Women's Fashion</a></li>
                    <li><a href="products.php">Kid's</a></li>
                </ul>
                <div class="footer-products-shortcut">
                    <a style="color: #029f6f;" href="products.php">Find More</a> <img src="../assets/greenright.png"
                        alt="">
                </div>
            </div>
            <div class="footer-info">
                <h4 class="third-category">Help & Support</h4>
                <ul>
                    <li><a href="contact.php">Contact Us</a></li>
                </ul>
            </div>
        </div>
        <div class="bottom-footer">
            <p>e-Tiangge Portal © 2024.<br>
                All Rights Reserved.</p>
            <img src="../assets/municipalitylogo.png" alt="">
            <img src="../assets/smiletaytay.png" alt="">
        </div>
    </footer>
</body>

</html>